version: '3.8'

services:
  nextjs-export-app:
    # image: nextjs-export-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-export-app
    ports:
      - '8000:8000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./out:/usr/share/nginx/html:ro
      - ./cogiscan-frontend:/var/www/html:ro
